server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active:
    - pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    tomcat:
      max-wait: 10000
      max-active: 300
      test-on-borrow: true
      initial-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    encoding: utf-8
    fallback-to-system-locale: false
  thymeleaf:
    encoding: UTF-8
  jmx:
    enabled: false
    default-domain: test
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true