spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sim_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: Dogness_ct2
  redis:
    host: localhost
    password: 
    port: 6379
    database: 3
